version: '3'

services:

  app-dvwa:
    image: irvinlim/owasp-dvwa
    ulimits:
      nofile: 8192

  app-juiceshop:
    image: bkimminich/juice-shop

  app-nowasp:
    image: citizenstig/nowasp
    environment:
      MYSQL_PASS: password

  app-securityninjas:
    image: irvinlim/owasp-securityninjas
    ulimits:
      nofile: 8192

  app-webgoat:
    image: danmx/docker-owasp-webgoat

  app-xvwa:
    image: tuxotron/xvwa
